apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: 'https://github.com/ahmedgabers/argocd-namespaces.git'
    targetRevision: HEAD
    path: deployments
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'test-namespace-2'
  syncPolicy:
    automated:
    prune: true
    selfHeal: true
    syncOptions:
      - CreateNamespace=true
